json.id product.id
json.supplier product.supplier.name
json.name product.name
json.price product.price
json.tax product.tax
json.total product.total
json.discounted? product.is_discounted?
json.in_stock product.in_stock
json.images product.image_url_list
json.description product.description